import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/header";
import Hero from "../components/hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Yesoke's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Hero />
        <Header />
        {children}
      </body>
    </html>
  );
}
